# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='时间')),
                ('weather', models.CharField(max_length=50, verbose_name='天气状况')),
                ('tem_max', models.IntegerField(verbose_name='最高温度')),
                ('tem_min', models.IntegerField(verbose_name='最低温度')),
                ('wind', models.CharField(max_length=50, verbose_name='风力')),
            ],
        ),
    ]
